### ISSUE TITLE
Desktop file doesn't work on Jolla C

### ISSUE THREAD

**Issue by Spritetm** [TylerTemp/fix-jolla-desktop#1]
I couldn't get the Alipay desktop file to actually start anything. I modified it to reflect the other files in the directory, and that got it working. Fyi, I ended up with the following:

[Desktop Entry]
Exec=apkd-launcher /home/.android/data/app/com.whatsapp-1.apk com.whatsapp/com.whatsapp.Main
Icon=/var/lib/apkd/apkd_launcher_com_whatsapp-com_whatsapp_Main.png
Name=WhatsApp
Type=Application
Version=1.0
X-Nemo-Application-Type=no-invoker
X-Nemo-Single-Instance=no
X-apkd-apkfile=/home/.android/data/app/com.whatsapp-1.apk
X-apkd-packageName=com.whatsapp

**Comment by TylerTemp** [comment]
Hey, thanks for your feedback. As I don't have a Jolla C, I can't reproduce this issue.

It looks like the apk file name is changed due to android version or the software version itself. Now
this script will try to find the  correct apk file on file system if one from `.desktop` file does not
exists.

Plz, feel free to reopen it if it does not fix at all.
